In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
kalamazoo_president = pd.read_csv('./kalamazoo-president.txt')
kalamazoo_straight_party = pd.read_csv('./kalamazoo-straight-party.txt')

In [11]:
kalamazoo_straight_party['sp_total'] = (
    kalamazoo_straight_party['dem'] +
    kalamazoo_straight_party['rep'] +
    kalamazoo_straight_party['lib'] +
    kalamazoo_straight_party['ust'] +
    kalamazoo_straight_party['wcp'] +
    kalamazoo_straight_party['grn'] +
    kalamazoo_straight_party['nlp']
)

kalamazoo_straight_party['percentage_republican'] = kalamazoo_straight_party['rep'] / kalamazoo_straight_party['sp_total']

In [9]:
kalamazoo_president['total_votes'] = (
  kalamazoo_president['biden'] +
  kalamazoo_president['trump'] +
  kalamazoo_president['jorgensen'] +
  kalamazoo_president['blankenship'] +
  kalamazoo_president['hawkins'] +
  kalamazoo_president['de_la_fuente'] +
  kalamazoo_president['w1'] +
  kalamazoo_president['w2'] +
  kalamazoo_president['w3'] +
  kalamazoo_president['w4'] +
  kalamazoo_president['w5'] +
  kalamazoo_president['w6']
)

In [10]:
kalamazoo_president

,precinct_name,biden,trump,jorgensen,blankenship,hawkins,de_la_fuente,w1,w2,w3,w4,w5,w6
0,Alamo Twp. 1,342,576,15,3,3,0,2,0,0,0,0,0
1,Alamo Twp. 2,588,915,23,5,5,0,2,0,0,0,0,0
2,Brady Twp. 1,561,936,23,3,4,0,1,0,0,0,0,0
3,Brady Twp. 2,416,843,19,3,6,0,1,0,0,0,0,0
4,Charleston Twp. 1,416,746,20,5,8,2,2,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,Portage City 16,1132,761,25,4,6,1,4,0,0,0,0,0
103,Portage City 17,822,714,17,1,4,3,4,0,0,0,0,0
104,Portage City 18,889,626,20,0,6,1,4,0,0,0,0,0
105,Portage City 19,871,484,16,2,4,0,1,0,0,0,0,0
106,Portage City 20,772,440,17,6,7,1,0,0,0,0,0,0